# simple dockerfile to test OCP s2i using Dockerfile 
# test buildConfig trigger again

FROM registry.access.redhat.com/ubi7:latest

CMD ["/bin/bash", "-c", "sleep infinity"]
# CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
